name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '5.0.x'
   
    - name: Add nuget.org as nuget package source
      run: dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Publish Artifact
      if: success()
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ${{ github.workspace }}/publish
